name: es6_math
description: Provides math functions from ES6 (ECMAScript 2015) that are currently missing in dart:math.
version: 1.0.0
repository: https://github.com/LeadRDRK/es6_math

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
